alias ls='\ls -F'
alias la='\ls -AF'
alias ll='\ls -AlF'
alias rm='\rm -i'
alias apting='sudo apt update;sudo apt upgrade'
alias dc-up='sudo service docker restart'
alias dc='docker container'
alias di='docker image'