default:
	@echo "usage: make help"

git:
	@mkdir -p ~/bin
	@rm -f ~/bin/git-prompt.sh ~/bin/git-completion.bash
	@wget -P ~/bin https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
	@wget -P ~/bin https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
